version: "3"


services:

  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=BS0880BSa
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    environment:
      - DB_NAME=prod_db
      - DB_USER=admin
      - DB_PASS=BS0880BSayamahaRGX612j
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=y&2c-*0hg^#at)k&kiv*9&1n)3hz^(uem%e&=7x7#x87qyw2t8
      - PRODUCTION=1
    volumes:
      - ./volumes/api/parsing_results:/usr/src/api/parsing_results
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - api
      - db
    ports:
      - "70:80"

  front:
    build:
      context: ./docker/front
      dockerfile: Dockerfile
    depends_on:
      - db
      - api
      - nginx
    ports:
      - "80:80"